run:
  timeout: 2m
  tests: true
linters:
  enable:
    - errcheck
    - govet
    - gosimple
    - staticcheck
    - typecheck
    - unused
    - revive
    - gofmt
    - goimports
    - depguard
linters-settings:
  errcheck:
    check-type-assertions: true
  revive:
    config: |
      ignoreGeneratedHeader = false
      severity = "warning"
      rules = [
        { name = "indent-error-flow" },
        { name = "var-naming" },
        { name = "blank-imports", severity = "error" },
        { name = "exported", severity = "warning" }
      ]
  gofmt:
    simplify: true
  depguard:
    list-type: blacklist
    packages:
      - fmt
    packages-with-error-message:
      fmt: "Use 'log' or structured logging instead of 'fmt' in core logic"
issues:
  exclude-use-default: false
  max-same-issues: 5
  max-issues-per-linter: 0
  max-issues: 0
  exclude-dirs:
    - bin
output:
  formats:
    - format: colored-line-number
