name: Unify Release Build
on:
  release:
jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build binary
        run: |
          mkdir -p bin
          OUTPUT_NAME=utify-${{ env.VERSION }}-${{ matrix.os }}-${{ matrix.arch }}
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o bin/$OUTPUT_NAME -ldflags "-s -w" .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: utify-binaries-${{ matrix.os }}-${{ matrix.arch }}
          path: bin/*
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: utify-binaries-*
          merge-multiple: true
          path: bin/
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
